# Generated by Django 6.0.7 on 2026-07-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_company_address_and_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_type',
            field=models.CharField(blank=True, default='Retail', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='currency_symbol',
            field=models.CharField(blank=True, default='Rs', max_length=10, null=True),
        ),
    ]
