# Generated by Django 6.0.7 on 2026-07-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_company_business_type_company_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_lifetime',
            field=models.BooleanField(default=False),
        ),
    ]
